<?php
/**
 * Copyright © Vendiro. All rights reserved.
 * See COPYING.txt for license details.
 */

use Vendiro\Connect\Block\Adminhtml\Config\Button\Credentials;

/**
 * @see \Vendiro\Connect\Block\Adminhtml\Config\Button\Credentials
 * @var Credentials $block
 */
?>
<script>
    require([
        'jquery',
        'prototype'
    ], function (jQuery) {
        var resultSpan = jQuery('.check-credentials-wrapper > #result_api');
        jQuery('#vendiro-button_credentials').click(function () {
            var params = {
                "mode": jQuery("input[name='groups[general][fields][mode][value]']").val(),
                "api_key": jQuery("input[name='groups[general][fields][api_key][value]']").val(),
                "api_token": jQuery("input[name='groups[general][fields][api_token][value]']").val(),
            };
            new Ajax.Request('<?= $block->escapeUrl($block->getApiCheckUrl()) ?>', {
                parameters: params,
                loaderArea: false,
                asynchronous: true,
                onCreate: function () {
                    resultSpan.find('.connecting').show();
                    resultSpan.find('.result').hide();
                },
                onSuccess: function (response) {
                    resultSpan.find('.connecting').hide();
                    var resultText = '';
                    if (response.status > 200) {
                        resultText = response.statusText;
                    } else {
                        var json = response.responseJSON;
                        if (typeof json.message != 'undefined') {
                            resultText = json.message;
                        }
                    }
                    resultSpan.find('.result').show();
                    resultSpan[0].querySelector('.result').innerHTML = resultText;
                }
            });
        });
    });
</script>

<div class="check-credentials-wrapper">
    <?= $block->getButtonHtml() ?>
    <div id="result_api">
        <span class="connecting" style="display: none;">Connecting...</span>
        <span class="result"></span>
    </div>
</div>